<require>
    <tag module="mofron-comp-text">Text</tag>
    <tag module="mofron-comp-button">Button</tag>
    <tag module="mofron-comp-linktxt">Link</tag>
    <tag module="mofron-comp-appbase">Appbs</tag>
    <tag module="mofron-comp-acdmenu">Menu</tag>
    <tag module="mofron-comp-bdritem">BdrItem</tag>
    <tag module="mofron-comp-borderhdg">BdrHeading</tag>
    <tag module="mofron-comp-accordion">Accrd</tag>
    <tag module="mofron-comp-footer">Footer</tag>
    <tag module="mofron-comp-frame">Frame</tag>
    <tag module="mofron-comp-login">Login</tag>
    <tag module="../comp/TagText.js">TagText</tag>
    <tag module="mofron-effect-fade">Fade</tag>
    <tag module="mofron-effect-shadow">Shadow</tag>
    <tag module="mofron-effect-border">Border</tag>
    <tag module="mofron-effect-hrzpos">Hrzpos</tag>
    <tag module="mofron-effect-synwhei">SynwHei</tag>
    <tag module="mofron-layout-grid">Grid</tag>
    <tag module="mofron-layout-margin">loMargin</tag>
    <tag module="mofron-layout-hrzcenter">HrzCent</tag>
    <tag module="mofron-event-click">Click</tag>
    <tag module="mofron-event-hover">Hover</tag>
    <tag src="./tag/docs/mcins.mof">McIns</tag>
    <tag src="./tag/docs/mccmp.mof">McCmp</tag>
    <tag src="./tag/docs/mcthm.mof">McThm</tag>
    <tag src="./tag/docs/mceff.mof">McEff</tag>
    <tag src="./tag/docs/mclay.mof">McLay</tag>
    <tag src="./tag/docs/mcevt.mof">McEvt</tag>
</require>

<responsive>
    <mobile orientation=portrait>800</mobile>
    <mobile orientation=landscape>1400</mobile>
    <tablet>800</tablet>
    <iPhone>3000</iPhone>
    <default>625</default>
</responsive>

<Appbs mainColor=240,230,250 effect=Fade(true,1000)>
    <title>
        <Text font="Iceland" style="font-size:0.45rem;">"mofron docs"</Text>
    </title>
    <style>-webkit-font-smoothing: antialiased;-moz-osx-font-smoothing: grayscale;</style>
    <theme>
        <Text mainColor=120,120,120></Text>
    </theme>
    <option>
        <header logo='./img/logo.png'></header>
    </option>
    <div layout=Grid([20,79])>
        <div baseColor=253,245,253>
            <effect>
                <Border type='right' color=190,190,190></Border>
            </effect>
            <layout>
                <loMargin>"left","0.2rem"</loMargin>
                <loMargin>"top","0.2rem"</loMargin>
            </layout>
            <Menu contents="mcins","mccmp","mcthm","mceff","mclay","mcevt" >
                <item>
                    <BdrItem accentColor=175,100,240>
                        <text><Text size="0.35rem" font="Iceland">Installation</Text></text>
                    </BdrItem>
                    <Accrd>
                        <headComp>
                             <Text size="0.35rem" font="Iceland">Quick Start</Text>
                        </headComp>
                        <BdrItem style="margin-left:0.15rem;" accentColor=175,100,240>
                            <text><Text size="0.3rem" font="Iceland">Component</Text></text>
                        </BdrItem>
                        <BdrItem style="margin-left:0.15rem;" accentColor=175,100,240>
                            <text><Text size="0.3rem" font="Iceland">Theme</Text></text>
                        </BdrItem>
                        <BdrItem style="margin-left:0.15rem;" accentColor=175,100,240>
                            <text><Text size="0.3rem" font="Iceland">Effect</Text></text>
                        </BdrItem>
                        <BdrItem style="margin-left:0.15rem;" accentColor=175,100,240>
                            <text><Text size="0.3rem" font="Iceland">Layout</Text></text>
                        </BdrItem>
                        <BdrItem style="margin-left:0.15rem;" accentColor=175,100,240>
                            <text><Text size="0.3rem" font="Iceland">Event</Text></text>
                        </BdrItem>
                    </Accrd>
                </item>
            </Menu>
        </div>
        <div baseColor=254,254,254>
            <McIns></McIns>
            <McCmp></McCmp>
            <McThm></McThm>
            <McEff></McEff>
            <McLay></McLay>
            <McEvt></McEvt>
        </div>
    </div>
</Appbs>
<Footer mainColor=190,190,190 baseColor=240,230,250 height="1rem">
    <Text effect=Hrzpos("center") style="margin-top:0.2rem;" mainColor=120,120,120 size="0.18rem">
        Released under the MIT License
    </Text>
</Footer>

<script run=init>
let txtclk = () => {
    alert('text click');
}
</script>

<script run=init>
let frmhvr = (p1,p2) => {
    if (true === p2) {
        p1.baseColor([240,230,250]);
    } else {
        p1.baseColor([255,255,255]);
    }
}
</script>

<script run=init name=fdbtn_clk>
try { mf.objkey.fdbtn.visible(true); } catch (e) {
    console.error(e.stack);
    throw e;
}
</script>
