<require>
    <tag module="mofron-comp-text">Text</tag>
    <tag module="mofron-comp-appbase">AppBase</tag>
    <tag module="mofron-effect-fade">Fade</tag>
    <tag module="mofron-comp-linktxt">Link</tag>
    <tag module="mofron-comp-aweicon">Icon</tag>
    <tag module="mofron-comp-prjtop">Prjtop</tag>
    <tag module="mofron-comp-image">Image</tag>
    <tag module="mofron-comp-footer">Footer</tag>
    <tag src="./tag/index/whats.mof">Whats</tag>
    <!-- event -->
    <tag module="mofron-event-link">evLink</tag>
    <!-- effect -->
    <tag module="mofron-effect-shadow">Shadow</tag>
    <tag module="mofron-effect-hrzpos">Hrzpos</tag>
    <tag module="mofron-effect-vrtpos">Vrtpos</tag>
    <!-- layout -->
    <tag module="mofron-layout-margin">Margin</tag>
</require>

<responsive>
    <mobile orientation=portrait>1100</mobile>
    <mobile orientation=landscape>800</mobile>
    <tablet>800</tablet>
    <default>625</default>
</responsive>

<AppBase color='#f0e6fa' effect=Fade(true,1000)>
    <param>
        <style>
            -webkit-font-smoothing: antialiased;
            -moz-osx-font-smoothing: grayscale;
            padding-bottom: 0.4rem;
        </style>
        <theme>
            <Text color='#787878' font=Iceland></Text>
        </theme>
        <title>mofron,"./img/logo.png"</title>
        <background>
            <div baseColor='#fafafa'></div>
        </background>
        <header param=navi>
            <div layout=Margin('left','0.2rem') style="display:flex;">
                <Link url=('./docs.html',true) size=0.25rem>Document</Link>
                <Icon link=('https://github.com/mofron/mofron',true) size=0.35rem>fab fa-github</Icon>
                <Icon link=('https://twitter.com/mofronjs',true) size=0.35rem>fab fa-twitter</Icon>
            </div>
        </header>
    </param>
    <Prjtop baseColor='#fdf5fd' name=prjtop offset=-40%>
        <image>
            <Image size=(2.5rem,2.5rem)>./img/mofron_tp.png</Image>
        </image>
        <text>Selectable UI as if you try clothes.</text>
        <button>Get Started,"./docs.html"</button>
    </Prjtop>
    <Whats></Whats>
</AppBase>

<Footer color=('#bebebe','#f0e6fa') height=1rem>
    <style>display:flex;</style>
    <Text color='#787878' size=0.3rem>
        <effect>
            <Hrzpos>center</Hrzpos>
            <Vrtpos>center</Vrtpos>
        </effect>
        <text>Released under the MIT License</text>
    </Text>
</Footer>
