<div name=mceff visible=false style="padding-bottom:0.3rem;" effect=Fade()>
    <layout>
        <HrzCent>80</HrzCent>
        <loMargin>"top","0.3rem"</loMargin>
    </layout>
    <BdrHeading mainColor=175,100,240>
        <text>
            <Text size="0.35rem" font="Iceland">Quick Start &gt; Effect</Text>
        </text>
    </BdrHeading>
    <div>
        <Text font="Quicksand" size="0.2rem">Effect is a function about designs and animations of components. It can be used by associating with a component. effect are made up of node modules.</Text>
        <Text font="Quicksand" size="0.2rem">It is possible to select and change flexibly according to the purpose. The following is Shadow and Fade effect samples. Other effects are also defined at 'mofron-effect-xxx' naming rules.</Text>
    </div>
    <BdrHeading mainColor=175,100,240>
        <text>
            <Text size="0.25rem" font="Iceland">Shadow Effect</Text>
        </text>
    </BdrHeading>
    <div>
        <Text font="Quicksand" size="0.2rem">Shadow effect is given shadow style to a component.</Text>
        <Text font="Quicksand" size="0.2rem">You can add shadow style to components without css know-how.</Text>
    </div>
    <div>
        <Text>Install effect:</Text>
        <Frame baseColor=245,245,250 height=null width="100%">
            <div style="padding:0.1rem;">
                <TagText>npm install mofron-effect-shadow</TagText>
            </div>
        </Frame>
    </div>
    <div>
        <Text>./tag/index.mof:</Text>
        <Frame baseColor=245,245,250 height=null width="100%">
            <div style="padding:0.1rem;">
                <TagText>&lt;require&gt;</TagText>
                <TagText indentConf=1>
                    &lt;tag module='mofron-comp-button'&gt;Button&lt;/tag&gt;
                </TagText>
                <TagText indentConf=1>
                    &lt;tag module='mofron-effect-shadow'&gt;Shadow&lt;/tag&gt;
                </TagText>
                <TagText>&lt;/require&gt;</TagText>
                <TagText>&lt;Button effect=Shadow()&gt;mofron&lt;/Button&gt;</TagText>
            </div>
        </Frame>
    </div>
    <div>
        <Text>Result:</Text>
        <div>
            <Frame width="100%" baseColor=255,255,255>
                <Button effect=Shadow()>mofron</Button>
            </Frame>
        </div>
    </div>
    <BdrHeading mainColor=175,100,240>
        <text>
            <Text size="0.25rem" font="Iceland">Fade Effect</Text>
        </text>
    </BdrHeading>
    <div>
        <Text font="Quicksand" size="0.2rem">Fade effect is given fade-in,fade-out animation to a component.</Text>
        <Text font="Quicksand" size="0.2rem">You can add fade animation to components without css know-how.</Text>
    </div>
    <div>
        <Text>Install effect:</Text>
        <Frame baseColor=245,245,250 height=null width="100%">
            <div style="padding:0.1rem;">
                <TagText>npm install mofron-effect-fade</TagText>
            </div>
        </Frame>
    </div>
    <div>
        <Text>./tag/index.mof:</Text>
        <Frame baseColor=245,245,250 height=null width="100%">
            <div style="padding:0.1rem;">
                <TagText>&lt;require&gt;</TagText>
                <TagText indentConf=1 >
                    &lt;tag module='mofron-comp-button'&gt;Button&lt;/tag&gt;
                </TagText>
                <TagText indentConf=1>
                    &lt;tag module='mofron-effect-shadow'&gt;Shadow&lt;/tag&gt;
                </TagText>
                <TagText indentConf=1>
                    &lt;tag module='mofron-effect-fade'&gt;Fade&lt;/tag&gt;
                </TagText>
                <TagText>&lt;/require&gt;</TagText>
                <TagText>&lt;Button&gt;</TagText>
                <TagText indentConf=1>&lt;effect&gt;</TagText>
                <TagText indentConf=2>&lt;Shadow&gt;&lt;/Shadow&gt;</TagText>
                <TagText indentConf=2>&lt;Fade&gt;true,1000&lt;/Fade&gt;</TagText>
                <TagText indentConf=1>&lt;/effect&gt;</TagText>
                <TagText indentConf=1>&lt;text&gt;mofron&lt;/text&gt;</TagText>
                <TagText>&lt;/Button&gt;</TagText>
            </div>
        </Frame>
    </div>
    <div>
        <div style="display:flex;">
            <Text>Result(</Text>
            <Text mainColor=0,115,187 event=Click(fdbtn_clk)>render</Text>
            <Text>):</Text>
        </div>
        <div>
            <Frame width="100%" baseColor=255,255,255>
                <Button name=fdbtn visible=false>
                    <effect>
                        <Shadow></Shadow>
                        <Fade>true,1000</Fade>
                    </effect>
                    <text>mofron</text>
                </Button>
            </Frame>
        </div>
    </div>
</div>
