<div name=mcins visible=false>
    <effect>
        <SynwHei></SynwHei>
        <Fade></Fade>
    </effect>
    <layout>
        <HrzCent>80</HrzCent>
        <loMargin>"top","0.3rem"</loMargin>
    </layout>
    <BdrHeading mainColor=175,100,240>
        <text>
            <Text size="0.35rem" font="Iceland">Installation</Text>
        </text>
    </BdrHeading>
    <Text size="0.3rem" font="Iceland">install mofron develop env:</Text>
    <Frame baseColor=245,245,250 height=null>
        <div style="padding:0.1rem;">
            <Text mainColor=50,50,50>
                git clone https://github.com/mofron/env-template.git (dirname)
            </Text>
            <Text mainColor=50,50,50>cd (dirname)</Text>
        </div>
    </Frame>
    <Text size="0.3rem" font="Iceland">install mofron core module:</Text>
    <Frame baseColor=245,245,250 height=null>
        <Text mainColor=50,50,50 style="padding:0.1rem;">npm install mofron</Text>
    </Frame>
</div>
