<Component baseColor=250,250,250 layout=Padding('top','0.2rem',false) width='100%'>
    <Text effect=Hrzpos('center') size='0.35rem'>"Why do we need a mofron ?"</Text>
    <Frame effect=efHrzcnt(65) layout=HrzCent(85) mainColor=240,230,250 baseColor=255,253,255 shadow='0.015rem'>
        <style>padding-bottom: 0.2rem; height:null;</style>
        <Component>
            <Text size="0.2rem">Today web development is tiresome for a sofware engineer. because it must need various things other than programming. For example, design and devices and browser and more...</Text>
            <Text size="0.2rem">css tuning and UI/UX design are very important. however, it is a load for a non web designer.</Text>
            <Text size="0.2rem">mofron aims to relieve the load of software engineers.</Text>
        </Component>
    </Frame>
</Component>
